import { Inter } from "next/font/google";
import "./sass/style.scss"
import Header from "./layout/header/page";
import Footer from "./layout/footer/page";
import { Box } from "@mui/material";
import { createContact } from "./apis";
const inter = Inter({ subsets: ["latin"] });
export const metadata = {
  title: "EECP website",
  description: "Generated by create next app",
};
const saveUserData = async () => {
  await createContact({});
}
saveUserData();
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body style={{ margin: 0 }}>
        <Header />
        <Box sx={{ marginTop: { xs: "94px", md: "101px" } }}>
          {children}
        </Box>
        <Footer />
      </body>
    </html>
  );
}
